In [5]:
import pandas as pd
import numpy as np

In [6]:
jvnq = pd.read_csv('vendas_modificado.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'vendas_modificado.csv'

In [ ]:
jvnq.head()

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca
0,13679,2021-03-20,23:35:51,LUCAS Araujo Kuhn,Queijo Mussarela,"R$ 16,87",13,239.31,Pagamento Confirmado,Niterói,RJ,Brasil,24000-000,20.0,Cartão de Crédito,SAMUEL HENRIQUE CAÇADOR,Porto Alegre
1,28070,2020-10-30,09:00:53,MICAEL SOUZA RONCETE,Molho de Tomate,"R$ 3,25",3,9.75,Pagamento Confirmado,Mariana,MG,Brasil,35420-000,0.0,Pix,MICAEL MALAQUIAS DE SOUZA OLIVEIRA,Fugini
2,47484,2021-06-09,15:30:28,FELIPE AUGUSTO NERY SILVA,Água Mineral,"R$ 1,63",9,36.67,Pagamento Confirmado,Cabo Frio,RJ,Brasil,28900-000,22.0,Transferência Bancária,HENRICO MATOS LIMA DA CUNHA,Minalba
3,20809,2022-06-04,08:41:23,LEVI RIBEIRO AMORIM,Carvão,"R$ 8,74",4,54.96,Em Separação,Campos dos Goytacazes,RJ,Brasil,28000-000,20.0,Pix,GABRIEL QUEIROZ DE AGUIAR,Marca-Brás
4,47123,2019-05-04,13:38:45,GABRIEL MATOS LIMA DA CUNHA,Café,"R$ 9,48",2,18.96,Em Separação,Conselheiro Lafaiete,MG,Brasil,36400-000,0.0,Cartão de Crédito,HENRICO MATOS LIMA DA CUNHA,3 Corações

In [ ]:
print(jvnq.dtypes)

id_da_compra      int64
data             object
hora             object
cliente          object
produto          object
valor            object
quantidade        int64
total           float64
status           object
cidade           object
estado           object
pais             object
cep              object
frete           float64
pagamento        object
vendedor         object
marca            object
dtype: object

In [ ]:
jvnq['data'] = pd.to_datetime(jvnq['data'], errors='coerce').dt.strftime('%Y-%m-%d')

In [ ]:
print(jvnq[['data', 'hora']].head())

         data      hora
0  2021-03-20  23:35:51
1  2020-10-30  09:00:53
2  2021-06-09  15:30:28
3  2022-06-04  08:41:23
4  2019-05-04  13:38:45

In [ ]:
colunas_numericas = ['quantidade', 'total', 'frete']

for coluna in colunas_numericas:
    jvnq[coluna] = pd.to_numeric(jvnq[coluna], errors='coerce')

print(jvnq.dtypes)

id_da_compra      int64
data             object
hora             object
cliente          object
produto          object
valor            object
quantidade        int64
total           float64
status           object
cidade           object
estado           object
pais             object
cep              object
frete           float64
pagamento        object
vendedor         object
marca            object
dtype: object

In [ ]:
jvnq.to_csv('vendas_corrigido.csv', index=False)

In [ ]:
print(jvnq[['produto']].head())

            produto
0  Queijo Mussarela
1   Molho de Tomate
2      Água Mineral
3            Carvão
4              Café

In [ ]:
import re

In [ ]:
jvnq['produto'] = jvnq['produto'].astype(str).apply(
    lambda x: re.sub(r'[^A-Za-z0-9À-ÿ\s]', '', x)
)

In [ ]:
print(jvnq[['produto']].head())

            produto
0  Queijo Mussarela
1   Molho de Tomate
2      Água Mineral
3            Carvão
4              Café

In [ ]:
jvnq.to_csv('vendas_corrigido.csv', index=False)

In [ ]:
print(jvnq.isnull().sum())

id_da_compra       0
data               0
hora               0
cliente            0
produto            0
valor              0
quantidade         0
total           3685
status             0
cidade             0
estado             0
pais               0
cep                0
frete           7371
pagamento          0
vendedor        3680
marca              0
dtype: int64

In [ ]:
jvnq.head(3)

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca
0,13679,2021-03-20,23:35:51,LUCAS Araujo Kuhn,Queijo Mussarela,"R$ 16,87",13,239.31,Pagamento Confirmado,Niterói,RJ,Brasil,24000-000,20.0,Cartão de Crédito,SAMUEL HENRIQUE CAÇADOR,Porto Alegre
1,28070,2020-10-30,09:00:53,MICAEL SOUZA RONCETE,Molho de Tomate,"R$ 3,25",3,9.75,Pagamento Confirmado,Mariana,MG,Brasil,35420-000,0.0,Pix,MICAEL MALAQUIAS DE SOUZA OLIVEIRA,Fugini
2,47484,2021-06-09,15:30:28,FELIPE AUGUSTO NERY SILVA,Água Mineral,"R$ 1,63",9,36.67,Pagamento Confirmado,Cabo Frio,RJ,Brasil,28900-000,22.0,Transferência Bancária,HENRICO MATOS LIMA DA CUNHA,Minalba

In [ ]:
jvnq['Frete_Check1'] = jvnq.groupby(['cidade', 'estado'])['frete'].transform('median')

In [ ]:
jvnq.head(3)

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca,Frete_Check1
0,13679,2021-03-20,23:35:51,LUCAS Araujo Kuhn,Queijo Mussarela,"R$ 16,87",13,239.31,Pagamento Confirmado,Niterói,RJ,Brasil,24000-000,20.0,Cartão de Crédito,SAMUEL HENRIQUE CAÇADOR,Porto Alegre,0.0
1,28070,2020-10-30,09:00:53,MICAEL SOUZA RONCETE,Molho de Tomate,"R$ 3,25",3,9.75,Pagamento Confirmado,Mariana,MG,Brasil,35420-000,0.0,Pix,MICAEL MALAQUIAS DE SOUZA OLIVEIRA,Fugini,0.0
2,47484,2021-06-09,15:30:28,FELIPE AUGUSTO NERY SILVA,Água Mineral,"R$ 1,63",9,36.67,Pagamento Confirmado,Cabo Frio,RJ,Brasil,28900-000,22.0,Transferência Bancária,HENRICO MATOS LIMA DA CUNHA,Minalba,22.0

In [ ]:
jvnq['Frete_Check2'] = jvnq.frete.fillna(jvnq.groupby (['cidade', 'estado'])['frete'].transform('median'))

In [ ]:
jvnq.head(3)

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca,Frete_Check1,Frete_Check2
0,13679,2021-03-20,23:35:51,LUCAS Araujo Kuhn,Queijo Mussarela,"R$ 16,87",13,239.31,Pagamento Confirmado,Niterói,RJ,Brasil,24000-000,20.0,Cartão de Crédito,SAMUEL HENRIQUE CAÇADOR,Porto Alegre,0.0,20.0
1,28070,2020-10-30,09:00:53,MICAEL SOUZA RONCETE,Molho de Tomate,"R$ 3,25",3,9.75,Pagamento Confirmado,Mariana,MG,Brasil,35420-000,0.0,Pix,MICAEL MALAQUIAS DE SOUZA OLIVEIRA,Fugini,0.0,0.0
2,47484,2021-06-09,15:30:28,FELIPE AUGUSTO NERY SILVA,Água Mineral,"R$ 1,63",9,36.67,Pagamento Confirmado,Cabo Frio,RJ,Brasil,28900-000,22.0,Transferência Bancária,HENRICO MATOS LIMA DA CUNHA,Minalba,22.0,22.0

In [ ]:
jvnq['frete'] =   jvnq.frete.fillna(jvnq.groupby (['cidade', 'estado'])['frete'].transform('median'))

In [ ]:
jvnq = jvnq.drop(columns=['Frete_Check1', 'Frete_Check2'])

In [ ]:
jvnq.head(3)

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca
0,13679,2021-03-20,23:35:51,LUCAS Araujo Kuhn,Queijo Mussarela,"R$ 16,87",13,239.31,Pagamento Confirmado,Niterói,RJ,Brasil,24000-000,20.0,Cartão de Crédito,SAMUEL HENRIQUE CAÇADOR,Porto Alegre
1,28070,2020-10-30,09:00:53,MICAEL SOUZA RONCETE,Molho de Tomate,"R$ 3,25",3,9.75,Pagamento Confirmado,Mariana,MG,Brasil,35420-000,0.0,Pix,MICAEL MALAQUIAS DE SOUZA OLIVEIRA,Fugini
2,47484,2021-06-09,15:30:28,FELIPE AUGUSTO NERY SILVA,Água Mineral,"R$ 1,63",9,36.67,Pagamento Confirmado,Cabo Frio,RJ,Brasil,28900-000,22.0,Transferência Bancária,HENRICO MATOS LIMA DA CUNHA,Minalba

In [ ]:
print(jvnq.isnull().sum())

id_da_compra       0
data               0
hora               0
cliente            0
produto            0
valor              0
quantidade         0
total           3685
status             0
cidade             0
estado             0
pais               0
cep                0
frete              0
pagamento          0
vendedor        3680
marca              0
dtype: int64

In [ ]:
jvnq.to_csv('vendas_corrigido.csv', index=False)

In [ ]:
def corrigir_valor(valor):
    match = re.search(r'\d{1,3}(,\d{2})?', str(valor))  
    if match:
        return match.group().replace(',', '.')
    return np.nan

jvnq['valor'] = jvnq['valor'].apply(corrigir_valor).astype(float)

In [ ]:
jvnq['total_calculado'] = jvnq['valor'] * jvnq['quantidade'] + jvnq['frete']

In [ ]:
jvnq[jvnq.total.isnull()].head(6)

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca,total_calculado
320,15092,2018-03-30,21:29:12,GUILHERME HUGO CAZULA PEREIRA,Feijão,10.19,2,NaN,Em Separação,Itaboraí,RJ,Brasil,24800-000,0.0,Cartão de Crédito,GABRIEL QUEIROZ DE AGUIAR,Caldo Bom,20.38
410,33369,2020-08-21,09:10:58,GABRIEL PAULO ALVES ALVIM,Refrigerante,6.21,2,NaN,Em Transporte,Angra dos Reis,RJ,Brasil,23900-000,0.0,Transferência Bancária,HENRICO MATOS LIMA DA CUNHA,Coca-Cola,12.42
448,28894,2022-01-09,15:55:37,THIAGO HENRIQUE CAÇADOR,Macarrão,2.49,14,NaN,Em Transporte,Cataguases,MG,Brasil,36770-000,0.0,Pix,LUCAS VITOR FAÇANHA NEVES,Renata,34.86
561,15983,2022-10-26,17:31:51,LUCAS RISSON EUZEBIO,Café,8.01,6,NaN,Em Separação,Astolfo Dutra,MG,Brasil,36780-000,0.0,Transferência Bancária,VICTOR GONÇALVES DONADONI,3 Corações,48.06
565,38996,2022-10-15,14:36:22,THIAGO CARDOSO DINIZ,Café,12.13,2,NaN,Pagamento Confirmado,São Bernardo do Campo,SP,Brasil,09700-000,0.0,Cartão de Crédito,MICAEL MALAQUIAS DE SOUZA OLIVEIRA,Melitta,24.26
580,21272,2020-09-05,10:45:01,PAULO SEGURASSE GONÇALVES,Sabonete,2.55,7,NaN,PC,Simão Pereira,MG,Brasil,36123-000,9.5,Cartão de Crédito,PAULO SOUZA RONCETE,Nivea,27.35

In [ ]:
jvnq['total'] = np.where(
    np.abs(jvnq['total'] - jvnq['total_calculado']) < 0.01,
    jvnq['total'],
    jvnq['total_calculado']
)

In [ ]:
jvnq.drop(columns=['total_calculado'], inplace=True)

In [ ]:
jvnq.head(6)

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca
0,13679,2021-03-20,23:35:51,LUCAS Araujo Kuhn,Queijo Mussarela,16.87,13,239.31,Pagamento Confirmado,Niterói,RJ,Brasil,24000-000,20.0,Cartão de Crédito,SAMUEL HENRIQUE CAÇADOR,Porto Alegre
1,28070,2020-10-30,09:00:53,MICAEL SOUZA RONCETE,Molho de Tomate,3.25,3,9.75,Pagamento Confirmado,Mariana,MG,Brasil,35420-000,0.0,Pix,MICAEL MALAQUIAS DE SOUZA OLIVEIRA,Fugini
2,47484,2021-06-09,15:30:28,FELIPE AUGUSTO NERY SILVA,Água Mineral,1.63,9,36.67,Pagamento Confirmado,Cabo Frio,RJ,Brasil,28900-000,22.0,Transferência Bancária,HENRICO MATOS LIMA DA CUNHA,Minalba
3,20809,2022-06-04,08:41:23,LEVI RIBEIRO AMORIM,Carvão,8.74,4,54.96,Em Separação,Campos dos Goytacazes,RJ,Brasil,28000-000,20.0,Pix,GABRIEL QUEIROZ DE AGUIAR,Marca-Brás
4,47123,2019-05-04,13:38:45,GABRIEL MATOS LIMA DA CUNHA,Café,9.48,2,18.96,Em Separação,Conselheiro Lafaiete,MG,Brasil,36400-000,0.0,Cartão de Crédito,HENRICO MATOS LIMA DA CUNHA,3 Corações
5,38623,2018-02-19,17:32:01,LUCAS ANTÔNIO DE SOUZA NETO,Café,10.16,1,20.16,Entregue com Sucesso,Resende Costa,MG,Brasil,36340-000,10.0,Transferência Bancária,VICTOR GONÇALVES DONADONI,3 Corações

In [ ]:
print(jvnq.isnull().sum())

id_da_compra       0
data               0
hora               0
cliente            0
produto            0
valor              0
quantidade         0
total              0
status             0
cidade             0
estado             0
pais               0
cep                0
frete              0
pagamento          0
vendedor        3680
marca              0
dtype: int64

In [ ]:
jvnq.to_csv('vendas_corrigido.csv', index=False)

In [ ]:
jvnq[jvnq.vendedor.isnull()].head(6)

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca
112,52388,2018-07-30,07:10:51,MIGUEL ANTÔNIO DE DECCO OLIVEIRA,Manteiga,8.77,5,56.85,Pagamento Confirmado,Juiz de Fora,MG,Brasil,36000-000,13.0,Cartão de Crédito,NaN,Aviação
425,46034,2019-12-28,14:14:40,RAFAEL HENRIQUE COSTA BARNABE MARAZO,Suco de Laranja,825.00,5,4125.00,Aguardando Pagamento,Leopoldina,MG,Brasil,367XXXXX,0.0,Boleto,NaN,Prats
525,30444,2022-09-11,21:39:42,LUCAS GONÇALVES DONADONI,Café,10.33,2,20.66,Em Separação,Niterói,RJ,Brasil,24000-000,-0.0,Transferência Bancária,NaN,3 Corações
543,41142,2020-10-16,12:47:08,GABRIEL CARLOS DE SOUZA,Vinho,28.89,1,28.89,Pagamento Confirmado,Coronel Xavier Chaves,MG,Brasil,36330-000,0.0,Cartão de Crédito,NaN,Miolo
544,194,2020-06-28,12:28:55,MATEUS Araujo Kuhn,Suco de Laranja,6.86,6,51.16,Em Separação,Lima Duarte,MG,Brasil,36140-000,10.0,Pix,NaN,Prats
623,55288,2020-05-08,14:08:29,SAMUEL HENRIQUE CAÇADOR,Queijo Mussarela,17.69,1,17.69,Entregue,Niterói,RJ,Brasil,24000-000,0.0,Transferência Bancária,NaN,Quatá

In [ ]:
jvnq['vendedor'] = jvnq['vendedor'].fillna('DESCONHECIDO')

In [ ]:
jvnq.head(6)

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca
0,13679,2021-03-20,23:35:51,LUCAS Araujo Kuhn,Queijo Mussarela,16.87,13,239.31,Pagamento Confirmado,Niterói,RJ,Brasil,24000-000,20.0,Cartão de Crédito,SAMUEL HENRIQUE CAÇADOR,Porto Alegre
1,28070,2020-10-30,09:00:53,MICAEL SOUZA RONCETE,Molho de Tomate,3.25,3,9.75,Pagamento Confirmado,Mariana,MG,Brasil,35420-000,0.0,Pix,MICAEL MALAQUIAS DE SOUZA OLIVEIRA,Fugini
2,47484,2021-06-09,15:30:28,FELIPE AUGUSTO NERY SILVA,Água Mineral,1.63,9,36.67,Pagamento Confirmado,Cabo Frio,RJ,Brasil,28900-000,22.0,Transferência Bancária,HENRICO MATOS LIMA DA CUNHA,Minalba
3,20809,2022-06-04,08:41:23,LEVI RIBEIRO AMORIM,Carvão,8.74,4,54.96,Em Separação,Campos dos Goytacazes,RJ,Brasil,28000-000,20.0,Pix,GABRIEL QUEIROZ DE AGUIAR,Marca-Brás
4,47123,2019-05-04,13:38:45,GABRIEL MATOS LIMA DA CUNHA,Café,9.48,2,18.96,Em Separação,Conselheiro Lafaiete,MG,Brasil,36400-000,0.0,Cartão de Crédito,HENRICO MATOS LIMA DA CUNHA,3 Corações
5,38623,2018-02-19,17:32:01,LUCAS ANTÔNIO DE SOUZA NETO,Café,10.16,1,20.16,Entregue com Sucesso,Resende Costa,MG,Brasil,36340-000,10.0,Transferência Bancária,VICTOR GONÇALVES DONADONI,3 Corações

In [ ]:
jvnq.to_csv('vendas_corrigido.csv', index=False)

In [ ]:
duplicatas = jvnq[jvnq.duplicated()]
print(duplicatas)

        id_da_compra        data      hora  \
9451           37102  2020-08-02  10:32:27
11787          43901  2019-07-20  13:10:10
13994           5337  2020-05-24  12:10:42
14387           2852  2018-08-26  17:38:01
14990          40818  2019-03-31  20:04:56
...              ...         ...       ...
368476         47230  2019-06-22  16:18:20
368503         50402  2022-06-25  08:13:33
368603         31673  2020-12-31  19:24:49
368628         14688  2019-01-06  18:01:24
368715         44677  2019-04-22  06:58:43

                                   cliente         produto  valor  quantidade  \
9451                 JOÃO SILVINO DA SILVA         Shampoo   7.65          12
11787               KALLEBE RIBEIRO AMORIM    Desinfetante   5.97           6
13994              GABRIEL VIEIRA DEMARQUE    Desinfetante   6.34           2
14387           MICAEL SEGURASSE GONÇALVES           Vinho  32.69          11
14990      TIAGO ANTÔNIO DE DECCO OLIVEIRA          Açúcar   2.99           2
...                                    ...             ...    ...         ...
368476   MATHEUS ANTÔNIO DE DECCO OLIVEIRA    Desinfetante   5.64          15
368503              GABRIEL WERNECK ELIZEU         Cerveja   2.54           8
368603               ARTHUR WERNECK ELIZEU         Shampoo   9.19          13
368628  YURI HENRIQUE COSTA BARNABE MARAZO  Pasta de Dente   3.45           8
368715                  LUCAS VICTOR ALVES    Óleo de Soja   4.08          12

         total                status                cidade estado    pais  \
9451     91.80          Em Separação                Viçosa     MG  Brasil
11787    45.32          Em Separação             São Tiago     MG  Brasil
13994    12.68         Em Transporte   São José dos Campos     SP  Brasil
14387   381.59  Pagamento Confirmado        Rio de Janeiro     RJ  Brasil
14990    15.98  Pagamento Confirmado        Matias Barbosa     MG  Brasil
...        ...                   ...                   ...    ...     ...
368476   84.60          Em Separação         Resende Costa     MG  Brasil
368503   30.82          Em Separação  Conselheiro Lafaiete     MG  Brasil
368603  127.97  Pagamento Confirmado             Tocantins     MG  Brasil
368628   27.60          Em Separação        Matias Barbosa     MG  Brasil
368715   59.96          Em Separação         Santos Dumont     MG  Brasil

              cep  frete               pagamento  \
9451    36570-000    0.0       Cartão de Crédito
11787   36350-000    9.5                     Pix
13994   12200-000    0.0       Cartão de Crédito
14387   20000-000   22.0  Transferência Bancária
14990   36120-000   10.0                  Boleto
...           ...    ...                     ...
368476  36340-000    0.0       Cartão de Crédito
368503  36400-000   10.5       Cartão de Crédito
368603  36510-000    8.5       Cartão de Crédito
368628  36120-000    0.0       Cartão de Crédito
368715  36240-000   11.0                  Boleto

                                    vendedor          marca
9451               GABRIEL QUEIROZ DE AGUIAR        Pantene
11787               CARLOS QUEIROZ DE AGUIAR           Veja
13994                   HENRICO VICTOR ALVES           Veja
14387            HENRICO MATOS LIMA DA CUNHA  Concha y Toro
14990            HENRICO MATOS LIMA DA CUNHA      Caravelas
...                                      ...            ...
368476                   PAULO SOUZA RONCETE      Pinho Sol
368503                  HENRICO VICTOR ALVES         Brahma
368603             GABRIEL QUEIROZ DE AGUIAR        Pantene
368628  FELIPE HENRIQUE COSTA BARNABE MARAZO        Sorriso
368715             LUCAS VITOR FAÇANHA NEVES          Coamo

[5359 rows x 17 columns]

In [ ]:
jvnq = jvnq.drop_duplicates()

In [ ]:
jvnq.to_csv('vendas_corrigido.csv', index=False)

In [ ]:
# Verificar dados faltantes
missing_data = jvnq.isnull().sum()
missing_data[missing_data > 0]

Series([], dtype: int64)

In [ ]:
espacos_extras = {}

text_cols = jvnq.select_dtypes(include='object').columns

for col in text_cols:
    espacos = jvnq[col].apply(lambda x: isinstance(x, str) and (x != x.strip()))
    if espacos.any():
        espacos_extras[col] = espacos.sum()

espacos_extras

{'cliente': np.int64(11053)}

In [ ]:
# Remover espaços em colunas do tipo texto
for col in jvnq.select_dtypes(include='object').columns:
    jvnq[col] = jvnq[col].astype(str).str.strip()

In [ ]:
# Remover linhas com dados faltantes
jvnq = jvnq.dropna()

In [ ]:
jvnq = jvnq.fillna("desconhecido")

In [ ]:
# Verificar valores negativos
df_valores_inconsistentes = jvnq[
    (jvnq["valor"] < 0) |
    (jvnq["quantidade"] < 0) |
    (jvnq["frete"] < 0) |
    (jvnq["total"] < 0)
]

df_valores_inconsistentes

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca
71,17370,2022-03-01,19:06:27,JOÃO QUEIROZ DE AGUIAR,Queijo Mussarela,16.51,14,221.14,Sep,Resende Costa,MG,Brasil,36340-000,-10.0,Pix,HENRICO MATOS LIMA DA CUNHA,Tirolez
99,21247,2022-01-20,16:06:33,MARCO SANTOS DA SILVA,Macarrão,454.57,13,5809.41,Aguardando Pagamento,Lagoa Dourada,MG,Brasil,36345-000,-100.0,Cartão de Crédito,MICAEL MALAQUIAS DE SOUZA OLIVEIRA,Adria
215,9551,2020-04-26,18:01:27,JOÃO DA CUNHA TEIXEIRA,Manteiga,8.37,12,82.44,Em Separação,São João de Meriti,RJ,Brasil,25500-000,-18.0,Cartão de Crédito,VICTOR GONÇALVES DONADONI,Qualy
382,8575,2022-04-23,12:01:48,YURI MUZY FERNANDES,Água Mineral,2.02,13,16.26,Transp,Tiradentes,MG,Brasil,36325-000,-10.0,Cartão de Crédito,HENRICO MATOS LIMA DA CUNHA,São Lourenço
451,19426,2020-04-23,19:51:29,JOÃO QUEIROZ DE AGUIAR,Sabonete,1.39,6,-0.16,Aguardando Pagamento,Tocantins,MG,Brasil,36510-000,-8.5,Transferência Bancária,GABRIEL QUEIROZ DE AGUIAR,Lux
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368491,24485,2021-02-16,03:32:56,KALLEBE SEGURASSE GONÇALVES,Açúcar,2.92,2,-4.16,Aguardando Pagamento,Belo Horizonte,MG,Brasil,30000-000,-10.0,Pix,CARLOS QUEIROZ DE AGUIAR,Caravelas
368594,16893,2019-03-05,03:17:24,BLENDOW CASTILHO CARDOSO,Amaciante,4.78,15,61.70,Aguardando Pagamento,Lima Duarte,MG,Brasil,36140-000,-10.0,Cartão de Crédito,HENRICO MATOS LIMA DA CUNHA,Downy
368635,43042,2020-10-25,10:58:55,JOÃO LACERDA PORTUGAL DA SILVA,Suco de Laranja,7.44,11,64.84,Pagamento Confirmado,Campinas,SP,Brasil,13000-000,-17.0,Transferência Bancária,MICAEL MALAQUIAS DE SOUZA OLIVEIRA,Del Valle
368684,35303,2021-03-13,09:18:57,PEDRO DA SILVA BIANQUINI,Farinha de Trigo,2.35,7,5.45,Em Transporte,Ubá,MG,Brasil,36500-000,-11.0,Cartão de Crédito,PAULO SOUZA RONCETE,Anaconda
368691,34012,2021-07-16,10:31:48,MARCO LACERDA PORTUGAL DA SILVA,Café,8.36,3,15.08,Aguardando Pagamento,Matias Barbosa,MG,Brasil,36120-000,-10.0,Transferência Bancária,MICAEL MALAQUIAS DE SOUZA OLIVEIRA,Pilão

In [ ]:
# Padronizar para minúsculo e sem espaços
jvnq['produto'] = jvnq['produto'].str.lower()

In [ ]:
# Ver produtos únicos antes da padronização
print("Antes:")
print(jvnq['produto'].unique())

# Padronizar
jvnq['produto'] = jvnq['produto'].str.strip().str.lower()

# Ver produtos únicos depois da padronização
print("Depois:")
print(jvnq['produto'].unique())

Antes:
['queijo mussarela' 'molho de tomate' 'água mineral' 'carvão' 'café'
 'feijão' 'condicionador' 'sabonete' 'açúcar' 'manteiga' 'papel higiênico'
 'óleo de soja' 'vinho' 'macarrão' 'shampoo' 'presunto' 'cerveja'
 'papel toalha' 'pasta de dente' 'pão de forma' 'sabão em pó' 'amaciante'
 'desinfetante' 'refrigerante' 'arroz' 'farinha de trigo'
 'biscoito recheado' 'sal' 'suco de laranja' 'leite integral' 'detergente'
 'refrigkrante' 'scl' 'papel qoalha' 'desinfetanue' 'qbeijo mussarela'
 'água mineras' 'presuntd' 'macawrão' 'sucoyde laranja' 'clfé'
 'desinfekante' 'majarrão' 'cnfé' 'farinha de tripo' 'manteigt' 'zabonete'
 'mqcarrão' 'arroc' 'tal' 'sabonepe' 'papel twalha' 'água mineual'
 'condicioiador' 'condibionador' 'caft' 'ieijão' 'açúcaz' 'amaciayte'
 'caff' 'mopho de tomate' 'molmo de tomate' 'biscoitq recheado' 'macirrão'
 'deqergente' 'cafc' 'queijo mussarelz' 'deterwente']
Depois:
['queijo mussarela' 'molho de tomate' 'água mineral' 'carvão' 'café'
 'feijão' 'condicionador' 'sabonete' 'açúcar' 'manteiga' 'papel higiênico'
 'óleo de soja' 'vinho' 'macarrão' 'shampoo' 'presunto' 'cerveja'
 'papel toalha' 'pasta de dente' 'pão de forma' 'sabão em pó' 'amaciante'
 'desinfetante' 'refrigerante' 'arroz' 'farinha de trigo'
 'biscoito recheado' 'sal' 'suco de laranja' 'leite integral' 'detergente'
 'refrigkrante' 'scl' 'papel qoalha' 'desinfetanue' 'qbeijo mussarela'
 'água mineras' 'presuntd' 'macawrão' 'sucoyde laranja' 'clfé'
 'desinfekante' 'majarrão' 'cnfé' 'farinha de tripo' 'manteigt' 'zabonete'
 'mqcarrão' 'arroc' 'tal' 'sabonepe' 'papel twalha' 'água mineual'
 'condicioiador' 'condibionador' 'caft' 'ieijão' 'açúcaz' 'amaciayte'
 'caff' 'mopho de tomate' 'molmo de tomate' 'biscoitq recheado' 'macirrão'
 'deqergente' 'cafc' 'queijo mussarelz' 'deterwente']

In [ ]:
# Manter apenas CEPs válidos
jvnq = jvnq[jvnq['cep'].astype(str).str.match(r'^\d{8}$')]

In [ ]:
jvnq.to_csv("vendas_corrigido.csv", index=False)

In [ ]:
# Reabrir pra conferir
jvnq_verificacao = pd.read_csv("vendas_corrigido.csv")
jvnq_verificacao.head()

Empty DataFrame
Columns: [id_da_compra, data, hora, cliente, produto, valor, quantidade, total, status, cidade, estado, pais, cep, frete, pagamento, vendedor, marca]
Index: []

## <p align="center"><strong><span style="color:blue;">Relatório Resumido</span></strong></p>

Etapas da Limpeza de Dados:
Datas:
Todas as datas foram padronizadas no formato internacional AAAA-MM-DD, facilitando a organização e a leitura dos registros.

Horários:
Os horários foram ajustados para o modelo de 24 horas, no formato HH:MM:SS, garantindo consistência nas análises envolvendo tempo.

Valores Numéricos:
As colunas com valores monetários e quantitativos como valor, quantidade, frete e total. Depois foram convertidas para tipos numéricos adequados (float ou int).

Durante esse processo, foram removidos símbolos como “R$” e vírgulas, adotando o ponto (.) como separador decimal. Para facilitar essa limpeza, utilizamos expressões regulares com a biblioteca re.

Tratamento de Dados Incompletos ou Duplicados:
Campos Vazios
Registros com informações essenciais faltando, como valor ou quantidade, foram removidos.
Já os campos que não comprometem a integridade dos dados foram preenchidos com estratégias específicas. Por exemplo, o frete foi substituído pela média dos valores existentes, e datas ausentes foram preenchidas com o valor mais frequente (moda).

Registros Duplicados:
Também foi feita uma verificação de duplicatas. Um total de X registros repetidos foi identificado e excluído, priorizando sempre a versão mais completa ou mais recente.

Correção do Campo "Total":
Para garantir que os valores do campo total estavam corretos, aplicamos a fórmula-padrão:

python
Copiar
Editar
total = (valor * quantidade) + frete
Quando identificamos divergências, os valores foram recalculados e atualizados com base nessa regra.

## <p align=""><strong>João Vitor Façanha Neves</span></strong></p>